version: "3.8"

# 默认日志配置
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "5"

# PHP环境
x-php: &default-php
  build: ./dockerfile/php
  #不想编译的可以直接使用镜像
  # image: ghcr.io/meowpay/sspanel:v2024_01_25

# 服务
services:

  # 代理服务器
  nginx:
    build: ./dockerfile/nginx
    # container_name: SSPanel-UimNginx
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/
      - ./SSPanel-Uim/:/var/www/SSPanel-Uim/
    ports:
      - 80:80
      # 不需要https注释掉下行
      - 443:443
    restart: always
    command: [ nginx, '-g', 'daemon off;' ]
    depends_on:
      - mysql
      - redis
    logging: *default-logging

  # Mariadb
  mysql:
    image: mariadb:latest
    # container_name: SSPanel-UimMysql
    environment:
      # 需要的话自行更改密码，但感觉没必要，在内网并不暴露端口
      - MARIADB_ROOT_PASSWORD=my-secret-pw
      - MARIADB_DATABASE=sspanel
    expose:
      - 3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    logging: *default-logging

  # PHP
  php:
    <<: *default-php
    # container_name: SSPanel-UimPHP
    volumes:
      - ./SSPanel-Uim/:/var/www/SSPanel-Uim/
      - ./data/socket/:/var/run/mysqld/
    expose:
      - 9000
    restart: always
    depends_on:
      - mysql
      - redis
    logging: *default-logging

  # Redis
  redis:
    # container_name: Redis
    image: redis:latest
    volumes:
      - ./data/redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    expose:
      - 6379
    restart: always
    logging: *default-logging

  # 定时任务
  cron:
    <<: *default-php
    volumes:
      - ./crontab:/crontab
      - ./SSPanel-Uim:/var/www/SSPanel-Uim
      - ./data/socket/:/var/run/mysqld/
    command: bash -c "crontab /crontab ;cron -f"
    depends_on:
      - php
    restart: always
    logging: *default-logging

  # 依赖安装
  php-compose:
    <<: *default-php
    # container_name: SSPanel-UimCompose
    volumes:
      - ./conf.d/:/etc/nginx/conf.d/
      - ./SSPanel-Uim/:/var/www/SSPanel-Uim/
    command: /bin/bash -c "cd /var/www/SSPanel-Uim;/usr/local/bin/composer install --ignore-platform-reqs --no-scripts --no-dev "
    logging: *default-logging
